{% set name = "markdown_strings" %}
{% set version = "3.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7574de0606160d7291ac2e1933a8ed47d31f0b49b674f128da1f548930c8578b

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  requires:
    - pytest
  imports:
    - markdown_strings

about:
  home: https://github.com/awesmubarak/markdown_strings/
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: 'This package allows the creation of markdown-compliant strings.'

  description: |
    Markdown is a markup language with plain text formatting syntax. This 
    package allows the creation of markdown-compliant strings.

extra:
  recipe-maintainers:
    - pvanheus
