travis:
  secure:
    BINSTAR_TOKEN: MwsUz52SxI7XKA6XGzttsKddEmHzbz7eFBgBMRb+jQkdA3UEd6T7jMnQZE11XThDcXMIK5w6QEOAGTdJveRpF1aSCz8P+Hfu+ZSL9hZnW9O5lUmp3CA6p0OhqePLBMk0VxeAq73T3EFqZo9QNII3LVMSlUNefnEjxrgcdtjQhE62AHzjjecpRp3aVPS3Q8/2iUmpHLWL+If2tnhxZI03SQpe84dGjVgUJbYG65BVwQFgFm4CWy6AcF1vdbmU41I50BCxxz3rUROfqS1IQPHXdOe9M5zLKerdDjnvvfa+6PazRSgdOMSxr4He21DweAsXIv7GloY5bANPjNtquYb+QvHLRkK7w13KYG/l9u9LptPcgxDwOk0RbTLdXsFTvhPzvVLNXCXspwLul2jyDX1yUQ0CFT8dkglmDj545++4/WVNq9fuQpBGqSTRD67HDSwSpdiFt0YPugA2xyDpbG0VNkVk7A4JVUI6qQe1R52PTkeK0VPCO8yY/56rWBrVmOnliV3qvDAJHK9/x7l8/kFVgw/PYQxiaTARnIFNO1jEEHn2xtzxP9W3g5BoLuqiBN3sjy3P4Spfs1aPxFfnMOBNQxTKAGSnMvHpcQibhgD7eHcRQPM75jX2sVGCHnZE0UeddSgKCDkD5yDUMrbgLjkMWHTLGhintYN6X0ogYTJwIXg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
